<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAdorzmn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAdorzmn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAdorzmn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAdorzmn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAdorzmn\appProdProjectContainer([
    'container.build_hash' => 'Adorzmn',
    'container.build_id' => 'dc04bbf2',
    'container.build_time' => 1622629715,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAdorzmn');
